# spring.application.name=api_gateway
# server.port=8082

app:
  api-prefix: /api/v1

server:
  port: 8090

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: lms
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/lms/**
          filters:
            - StripPrefix=2
